# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Violent Vixen PR
email: theviolentvixenpr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Provides Blog Tours & other publicity to authors & publishers using tried & true methods in conjunction with new, exciting, and fun ideas
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://courtneydion.github.io/vvpr" # the base hostname & protocol for your site
twitter_username: theviolentvixen
github_username: CourtneyDion

# Build settings
markdown: kramdown
